// Report Generation — daily threat briefing in Markdown and HTML

export function generateDailyReport(sweepData, delta, memory) {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];

  const sources = sweepData?.sources || {};
  const meta = sweepData?.crucix || {};

  const sections = [];

  // Header
  sections.push(`# Crucix Daily Threat Intelligence Report`);
  sections.push(`**Date:** ${dateStr}`);
  sections.push(`**Generated:** ${now.toISOString()}`);
  sections.push(`**Sources:** ${meta.sourcesOk || 0}/${meta.sourcesQueried || 0} active`);
  sections.push('');

  // Threat Overview
  if (delta) {
    sections.push(`## Threat Overview`);
    sections.push(`- **Threat Level:** ${delta.overallLevel || 'UNKNOWN'}`);
    sections.push(`- **Threat Index:** ${delta.threatIndex || 0}/100`);
    sections.push(`- **Direction:** ${delta.direction || 'stable'}`);
    sections.push(`- **Signals:** ${delta.summary?.totalSignals || 0} (${delta.summary?.criticalCount || 0} critical, ${delta.summary?.highCount || 0} high)`);
    sections.push('');

    if (delta.signals?.correlated?.length > 0) {
      sections.push(`### Cross-Correlation Alerts`);
      for (const c of delta.signals.correlated) {
        sections.push(`- **[${c.level}] ${c.name}**: ${c.evidence?.join(', ') || ''}`);
      }
      sections.push('');
    }
  }

  // CVE Section
  const nvdCVEs = sources['NVD']?.recentCVEs || [];
  const critCVEs = nvdCVEs.filter(c => (c.cvssScore || c.cvss || 0) >= 9.0);
  const kevEntries = sources['CISA-KEV']?.recentAdditions || sources['CISA-KEV']?.vulnerabilities || [];

  sections.push(`## Vulnerability Intelligence`);
  sections.push(`- **Total CVEs tracked:** ${nvdCVEs.length}`);
  sections.push(`- **Critical (CVSS≥9.0):** ${critCVEs.length}`);
  sections.push(`- **In CISA KEV:** ${kevEntries.length}`);

  if (critCVEs.length > 0) {
    sections.push('');
    sections.push('### Critical CVEs');
    for (const c of critCVEs.slice(0, 10)) {
      sections.push(`- **${c.cveId || c.id}** (CVSS: ${c.cvssScore || c.cvss || '?'}) — ${(c.description || '').substring(0, 120)}`);
    }
  }
  sections.push('');

  // Ransomware Activity
  const victims = sources['Ransomware-Live']?.victims || [];
  if (victims.length > 0) {
    sections.push(`## Ransomware Activity`);
    sections.push(`- **Recent Victims:** ${victims.length}`);
    const byGroup = sources['Ransomware-Live']?.byGroup || {};
    const topGroups = Object.entries(byGroup).sort((a, b) => b[1] - a[1]).slice(0, 5);
    if (topGroups.length > 0) {
      sections.push('### Top Active Groups');
      for (const [name, count] of topGroups) {
        sections.push(`- ${name}: ${count} victims`);
      }
    }
    sections.push('');
  }

  // CERT Advisories
  const certTotal = (sources['CISA-Alerts']?.totalAlerts || 0) +
    (sources['ENISA']?.totalReports || 0) + (sources['CERTs-Intl']?.totalAlerts || 0);
  if (certTotal > 0) {
    sections.push(`## CERT Advisories (${certTotal} total)`);
    for (const alert of (sources['CISA-Alerts']?.recentAlerts || []).slice(0, 5)) {
      sections.push(`- [CISA] ${alert.title || ''}`);
    }
    for (const alert of (sources['ENISA']?.recentReports || []).slice(0, 3)) {
      sections.push(`- [ENISA] ${alert.title || ''}`);
    }
    sections.push('');
  }

  // China Intelligence
  const cnAlerts = (sources['CNCERT']?.totalAlerts || 0) +
    (sources['CNVD']?.recentVulns?.length || 0) + (sources['CNNVD']?.recentVulns?.length || 0);
  if (cnAlerts > 0) {
    sections.push(`## China Intelligence (${cnAlerts} items)`);
    for (const a of (sources['CNCERT']?.recentAlerts || []).slice(0, 3)) {
      sections.push(`- [CNCERT] ${a.title || ''}`);
    }
    for (const v of (sources['CNVD']?.recentVulns || []).slice(0, 3)) {
      sections.push(`- [CNVD] ${v.id || ''}: ${v.title || ''}`);
    }
    sections.push('');
  }

  // CVE Lifecycle
  if (memory?.getCVETracker) {
    const tracker = memory.getCVETracker();
    const trackedIds = Object.keys(tracker);
    if (trackedIds.length > 0) {
      sections.push(`## CVE Lifecycle Tracking (${trackedIds.length} CVEs)`);
      const withKEV = trackedIds.filter(id => tracker[id].stages?.includes('kev'));
      const withPoc = trackedIds.filter(id => tracker[id].stages?.includes('poc'));
      sections.push(`- In KEV: ${withKEV.length}`);
      sections.push(`- With PoC: ${withPoc.length}`);
      sections.push('');
    }
  }

  // Source Health
  sections.push(`## Source Health`);
  sections.push(`- Active: ${meta.sourcesOk || 0}/${meta.sourcesQueried || 0}`);
  if (sweepData?.errors?.length > 0) {
    sections.push('### Failed Sources');
    for (const e of sweepData.errors) {
      sections.push(`- ${e.name}: ${e.error}`);
    }
  }
  sections.push('');
  sections.push('---');
  sections.push(`*Generated by Crucix Cybersecurity Intelligence Engine v${meta.version || '1.0.0'}*`);

  return sections.join('\n');
}

export function generateReportHTML(markdown) {
  return markdown
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    .replace(/\n\n/g, '<br><br>')
    .replace(/^---$/gm, '<hr>');
}
